name=TimerStatic
version=2.2.0
author=DashyFox
maintainer=DashyFox
sentence=Библиотека статических таймеров для Arduino с поддержкой обратных вызовов
paragraph=Лёгкая библиотека таймеров, которая предоставляет статическую функциональность таймеров с поддержкой различных типов обратных вызовов, включая указатели на функции, лямбда-функции и объектно-ориентированные обратные вызовы. Возможности включают управление жизненным циклом на основе счётчиков и времени, функциональность задержки и эффективное управление памятью.
category=Timing
url=https://github.com/dashyfox/TimerStatic
architectures=*
depends=
includes=TimerStatic.h
size=2048
