[platformio]
description = TimerStatic Library
src_dir = src
lib_dir = .

[env:native]
platform = native
build_flags = -std=gnu++11
lib_deps = 
    throwtheswitch/Unity@^2.5.2

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:esp8266]
platform = espressif8266
board = esp8266
framework = arduino

[env:stm32f103c8t6]
platform = ststm32
board = stm32f103c8t6
framework = arduino

[env:rpipico]
platform = raspberrypi
board = rpipico
framework = arduino
